### ISSUE TITLE
How did you creat the maping ?

### ISSUE THREAD

**Issue by sucrecacao** [pacha/vem#2]
Hello,

From vem-editor.org:
>  The commands are also distributed spatially across the keyboard, like in a map, optimizing their position according to their frequency:

I'm curious about which method you used to created this innovative mapping ?

**Comment by pacha** [comment]
Hi @sucrecacao,
There were a couple of principles I wanted to follow from the beginning and others that came clear later when working on different combinations (all the examples are for `QWERTY` here):

* Initially every (letter) key had 4 possible commands: lower and uppercase, combined with `ctrl` and combined with `alt`. I dropped `alt` early on to ensure compatibility with system commands on some platforms and to lower the number of total commands. (To compensate the lost of key combinations the final version of the mapping includes some commands prefixed with `Space`).
* I wanted every basic action that one can expect in any editor to be represented as a key command. One example of this is opening files or quickly switching between them. (For instance, Vim provides ex-commands for those, but not keyboard ones).
* After many tests I noticed that commands that could be potentially pressed repeatedly don't work very well when assigned to the ring or little finger. That's why actions like `c` (delete line), `U` (page up), `M` (page down), `Y` (prev quickfix item) or `N` (next quickfix item) among others are not assigned to the first ones.
* The spatial relationship between commands is very important in Vem. That's why `a` (go to top) is just immediately above `z` (go to bottom) or why `i` (insert mode to the left of current char) is next to `o` (insert mode to the right of current chart)...
* Also no spatial relationships could be used for symbols since they change vastly depending on the language of the keyboard.
* Originally,  the basic movement keys (`hjkl`) were assigned to the right hand but in a different distribution when compared to Vim's one. That setup was more intuitive and worked really well but I gave it up very late in the process since `hjkl` is a standard by now and it is used in plenty of different contexts beyond Vim itself.
* I wanted some actions to be assigned to the left hand, so they could be alternated with the right one: clipboard commands, commenting source code, some selections and switching files were some of them. Also clipboard commands had to be able to be used without having to use any modifier key.

But all of these are just examples. What mattered at the end of the day was that whichever combination I was testing, it had to work in practice. I lost count of how many arrangements I thought that they were an awesome idea just to find that they just didn't work. This continuous testing of different possibilities made the project to stretch during a long, long time (many years). Every time you move one single command, you have to find a solution for the key that is already assigned to the targeted key and, potentially, to neighbor keys too. Also, you don't know if something works right away because the first impression is that it doesn't, since you're not used to the new configuration. So you have to give it time (weeks or months, depending on the change) before you can start evaluating if the change made sense. Eventually, some commands were settling down up to the point of filling most of the keyboard. That happened around a year ago and since them I just made small fixes and wrote the documentation of the project.
